---
- name: rabbitmq_users | creating rabbitmq users
  rabbitmq_user:
    name: "{{ item['name'] }}"
    password: "{{ item['password'] }}"
    vhost: "{{ item['vhost']|default(omit) }}"
    configure_priv: "{{ item['configure_priv']|default(omit) }}"
    read_priv: "{{ item['read_priv']|default(omit) }}"
    write_priv: "{{ item['write_priv']|default(omit) }}"
    tags: "{{ item['tags']|default(omit) }}"
    permissions: "{{ item['permissions']|default(omit) }}"
    state: present
  run_once: rabbitmq_enable_clustering is defined and rabbitmq_enable_clustering
  delegate_to: "{{ rabbitmq_master|default(omit) }}"
  become: true
  with_items: "{{ rabbitmq_users }}"
  when: rabbitmq_debian_version is version('3.7.9', '<')

- name: rabbitmq_users | creating rabbitmq users (rabbit >= 3.7.9)
  rabbitmq_user_3_7_9:
    name: "{{ item['name'] }}"
    password: "{{ item['password'] }}"
    vhost: "{{ item['vhost']|default(omit) }}"
    configure_priv: "{{ item['configure_priv']|default(omit) }}"
    read_priv: "{{ item['read_priv']|default(omit) }}"
    write_priv: "{{ item['write_priv']|default(omit) }}"
    tags: "{{ item['tags']|default(omit) }}"
    permissions: "{{ item['permissions']|default(omit) }}"
    state: present
  run_once: rabbitmq_enable_clustering is defined and rabbitmq_enable_clustering
  delegate_to: "{{ rabbitmq_master|default(omit) }}"
  become: true
  with_items: "{{ rabbitmq_users }}"
  when: rabbitmq_debian_version is version('3.7.9', '>=')
